
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Mar 24 18:21:58 GMT-06:00 2018
//----------------------------------------------------

package proyectocompi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_ARRAY = 47;
  public static final int TK_INT = 12;
  public static final int TK_SEMICOLON = 29;
  public static final int TK_CASE = 5;
  public static final int TK_LPAREN = 23;
  public static final int TK_FOR = 10;
  public static final int TK_COMMA = 30;
  public static final int TK_RPAREN = 24;
  public static final int TK_OPREL = 35;
  public static final int INT = 45;
  public static final int TK_IF = 13;
  public static final int TK_MINUSMINUS = 37;
  public static final int COMMENT_BEGIN = 41;
  public static final int WHITESPACE = 40;
  public static final int TK_DOT = 31;
  public static final int TK_BOOLEAN = 3;
  public static final int LETRA = 43;
  public static final int ENDLINE = 39;
  public static final int TK_RETURN = 16;
  public static final int TK_BREAK = 4;
  public static final int TK_ASIG = 32;
  public static final int DIGIT = 44;
  public static final int TK_TRUE = 20;
  public static final int ID = 38;
  public static final int TK_NULL = 22;
  public static final int EOF = 0;
  public static final int TK_LBRACK = 27;
  public static final int error = 1;
  public static final int TK_SWITCH = 15;
  public static final int TK_WHILE = 17;
  public static final int TK_LBRACE = 25;
  public static final int TK_DEFAULT = 11;
  public static final int TK_ELSE = 9;
  public static final int TK_RBRACK = 28;
  public static final int TK_FUNC = 8;
  public static final int TK_OPLOG = 33;
  public static final int TK_RBRACE = 26;
  public static final int TK_FALSE = 21;
  public static final int TK_THEN = 14;
  public static final int TK_STRING = 7;
  public static final int COMMENT_END = 42;
  public static final int TK_PLUSPLUS = 36;
  public static final int TK_PRINT = 18;
  public static final int STRING = 46;
  public static final int TK_VARIABLE_TIPO = 2;
  public static final int TK_INPUT = 19;
  public static final int TK_OPMAT = 34;
  public static final int TK_CHAR = 6;
}

