/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_analisisalgoritmos;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author leirA
 */
public class Main extends javax.swing.JFrame {

    TSP_Grafo_Agente Grafo_Agente_Reutilizable;
    ArrayList<Knapsack_Mochila> Multiples_Mochilas = new ArrayList<Knapsack_Mochila>();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Final NP + NP Completo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Análisis de Algoritmos");

        jButton2.setText("TSP");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Knapsack");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(112, 112, 112))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        IniciarTSP();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        IniciarKnapsack();
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void IniciarTSP() {
        Grafo_Agente_Reutilizable = new TSP_Grafo_Agente();
        Dimension size = Toolkit.getDefaultToolkit().getScreenSize();
        Grafo_Agente_Reutilizable.setUndecorated(!true);
        Grafo_Agente_Reutilizable.setSize(500, 500);
        Grafo_Agente_Reutilizable.setVisible(true);
    }

    private void IniciarKnapsack() {
        JOptionPane.showMessageDialog(this, "Iniciemos el robo");
        Knapsack_Elemento Nuevo_Elemento;
        Knapsack_Mochila Nueva_Mochila;
        int ValorTotal;
        int PesoTotal;
        int EsPeso; //respuesta 1 si es por peso
        int Numero_Mochilas = Integer.parseInt(JOptionPane.showInputDialog("Ingrese la cantidad de mochilas que desea llevar para este robo:"));
        for (int i = 1; i <= Numero_Mochilas; i++) {
            EsPeso = Integer.parseInt(JOptionPane.showInputDialog("Ingrese si la mochila " + i + " es por \n 1. Peso \n 2. Valor"));
            if (EsPeso == 1) {
                PesoTotal = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el peso maximo de la mochila " + i));
                Nueva_Mochila = new Knapsack_Mochila(PesoTotal, 0, true);
                this.Multiples_Mochilas.add(Nueva_Mochila);
            } else {
                if (EsPeso == 2) {
                    ValorTotal = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el valor maximo de la mochila " + i));
                    Nueva_Mochila = new Knapsack_Mochila(0, ValorTotal, false);
                    this.Multiples_Mochilas.add(Nueva_Mochila);
                } else {
                    JOptionPane.showMessageDialog(this, "No ha ingresado una opcion valida");
                    i--;
                }
            }
        }
        boolean robar = true;
        boolean ingresado = false;
        int Pos_Mochila = 0;
        while (robar) { //Entramos a la casa y vemos que podemos robar
            EsPeso = Integer.parseInt(JOptionPane.showInputDialog("UN ARTICULO!, quieres tomarlo por su: \n 1. Peso \n 2. valor \n 3. Salir Corriendo"));
            ingresado = false;
            Pos_Mochila = 0;
            //verificamos lo que queremos robar y en seguida comprobamos si lo podemos robar
            //Si lo podemos robar entonces lo metemos en la primera mochila que quepa y seguimos
            if (EsPeso == 1) {
                //Verifica insertar por peso
                PesoTotal = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el peso del articulo: "));
                Nuevo_Elemento = new Knapsack_Elemento(PesoTotal, 0);
                while (!ingresado) {
                    if (this.Multiples_Mochilas.get(Pos_Mochila).Es_Peso) {
                        if (this.Multiples_Mochilas.get(Pos_Mochila).NuevoArticulo(Nuevo_Elemento)) {
                            ingresado = true;
                            Pos_Mochila = 0;
                        } else {
                            Pos_Mochila++;
                            JOptionPane.showMessageDialog(null, "No se puede agregar el elemento a la mochila " + Pos_Mochila + ", sobrepasa el peso, se sigue buscando");
                        }
                    }
                    if (Pos_Mochila == this.Multiples_Mochilas.size()) {
                        JOptionPane.showMessageDialog(this, "Ya no le queda espacio en ninguna mochila");
                        ingresado = true;
                    }else{
                        Pos_Mochila++;
                    }
                }
            } else {
                //Verifica insertar por valor
                if (EsPeso == 2) {
                    ValorTotal = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el  valor del articulo: "));
                    Nuevo_Elemento = new Knapsack_Elemento(0, ValorTotal);
                    while (!ingresado) {
                        if (!this.Multiples_Mochilas.get(Pos_Mochila).Es_Peso) {
                            if (this.Multiples_Mochilas.get(Pos_Mochila).NuevoArticulo(Nuevo_Elemento)) {
                                ingresado = true;
                                Pos_Mochila = 0;
                            } else {
                                Pos_Mochila++;
                                JOptionPane.showMessageDialog(null, "No se puede agregar el elemento a la mochila " + Pos_Mochila + ", sobrepasa el valor, se sigue buscando");
                            }
                        }
                        if (Pos_Mochila == this.Multiples_Mochilas.size()) {
                            JOptionPane.showMessageDialog(this, "Ya no le queda espacio en ninguna mochila");
                            ingresado = true;
                        }Pos_Mochila++;
                    }
                } else {
                    //Si escuchamos un ruido nos vamos y estando a salvo hacemos conteo de lo que hemos robado
                    if (EsPeso == 3) {
                        JOptionPane.showMessageDialog(this, "VAMONOS DE AQUI!!!");
                        ingresado = true;
                        robar = false;
                    } else {
                        JOptionPane.showMessageDialog(this, "Ingrese una Opcion valida");
                    }
                }
            }
        }
        Imprimir_Mochilas();
        //Imprimimos
        Reiniciar();
        //vaciamos el contenido para otro atraco :3
    }

    private void Imprimir_Mochilas() {
        //Hacemos la impresion de todo lo que robamos
        String toString = "Articulos en Mochilas \n";
        for (int i = 0; i < this.Multiples_Mochilas.size(); i++) {
            toString += "Mochila: " + i + " \n ";
            toString += this.Multiples_Mochilas.get(i).ElementosDentro();
        }
        JOptionPane.showMessageDialog(this, toString);
    }

    private void Reiniciar() {
        this.Multiples_Mochilas.clear();
    }

}
